apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-sql-proxy
spec:
  selector:
    matchLabels:
      app: cloud-sql-proxy
  template:
    metadata:
      labels:
        app: cloud-sql-proxy
    spec:
      containers:
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command:
          - "/cloud_sql_proxy"
          - "-instances={{ .Values.project }}:{{ .Values.region }}:{{ .Values.database }}=tcp:0.0.0.0:5432"
          - "-credential_file=/secrets/service_account.json"
        securityContext:
          runAsNonRoot: true
        volumeMounts:
        - name: sa-secret-vol
          mountPath: /secrets/
          readOnly: true
      volumes:
      - name: sa-secret-vol
        secret:
          secretName: {{ .Values.secret }}