apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployments.controller.name }}-svc
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: controller
